### ISSUE TITLE
Did Not Import Correctly

### ISSUE THREAD

**Issue by Havoc4Hire** [wlvchandler/PuTTY-Ubuntu-Theme#2]
*.reg file was not importing directly into registry properly on Windows 10 Pro. Updated file for it to work properly See Attatched. 
[ubuntu.zip](https://github.com/wlvchandler/PuTTY-Ubuntu-Theme/files/6573327/ubuntu.zip)

**Comment by lepantella** [comment]
I've added the feature to import this for all sessions automatically: #4

**Comment by wlvchandler** [comment]
> I've added the feature to import this for all sessions automatically: #4

Thanks, I merged it. Apologies it took so long - I must have missed the notifications about both of these comments
